openapi: 3.0.2
info:
  title: ANZ Wholesale
  description: The sample application being requested by the candidate to build the backend REST APIs
    needed to support a web application to that allows a user to view accounts and
    subsequently view transactions on any of the accounts they hold.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1

paths:
  /accounts:
    get:
      description: get account list with details
      responses:
        200:
          description: A list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'

  /accounts/{accountNumber}/transactions:
    get:
      description: get account transactions
      parameters:
        - in: path
          name: accountNumber
          schema:
            type: integer
            format: int64
            example: 585309209
      responses:
        200:
          description: A list of account's transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'


components:
  schemas:
    BaseAccount:
      type: object
      properties:
        number:
          type: integer
          format: int64
          example: 585309209
        name:
          type: string
          example: SGSavings726
        currency:
          type: string
          enum: [SGD, AUD]

    Account:
      allOf:
        - $ref: '#/components/schemas/BaseAccount'
        - type: object
          properties:
            type:
              type: string
              enum: [ Savings, Current ]
            balanceDate:
              type: string
              format: date
              example: 08/11/2018
            openingAvailableBalance:
              type: number
              format: decimal
              example: 84327.51

    Transaction:
      allOf:
        - $ref: '#/components/schemas/BaseAccount'
        - type: object
          properties:
            number:
              type: integer
              format: int64
              example: 123-2223-212
            valueDate:
              type: string
              format: date
              example: Jan. 12, 2012
            debitAmound:
              type: number
              format: decimal
              example:
            creditAmount:
              type: number
              format: decimal
              example: 9540.98
            debitCredit:
              type: string
              enum: [ Debit, Credit ]
              example: Credit
            narrative:
              type: string
              example: ''







